# Generated by Django 4.1.5 on 2023-02-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='year',
            field=models.IntegerField(),
        ),
    ]
